# Generated by Django 6.0 on 2026-08-16 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_workspace_user_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='message_quota',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WorkspaceDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message_count', models.BigIntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'date'), name='uniq_workspace_daily_usage')],
            },
        ),
    ]
