# Generated by Django 6.0 on 2026-08-24 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_workspace_message_quota_workspacedailyusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='allowed_origins',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='WorkspaceWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2048)),
                ('secret', models.CharField(max_length=128)),
                ('events', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
