# Generated by Django 6.0 on 2026-01-04 02:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_messagereadreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messaging_m_group_i_554188_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messaging_m_recipie_e21d7b_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-created_at'], name='message_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type', '-created_at'], name='message_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['group', '-created_at'], name='message_group_created_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'recipient', '-created_at'], name='message_private_created_idx'),
        ),
    ]
