# Generated by Django 6.0 on 2026-01-04 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_message_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='message_created_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='message_type_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='message_group_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='message_private_created_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type', 'group', '-created_at'], name='messaging_m_message_0872e9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type', 'sender', 'recipient', '-created_at'], name='messaging_m_message_e22aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='messaging_m_sender__9b0bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', '-created_at'], name='messaging_m_recipie_3abcda_idx'),
        ),
    ]
