# Generated by Django 6.0 on 2026-08-16 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_workspace_user_workspace'),
        ('messaging', '0007_message_parent_message_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='accounts.workspace'),
        ),
    ]
